name: Deploy to Windows
# on:
#   pull_request:
#     types: [closed]
#     branches:
#       - main  # Only trigger for PRs merged into main
on: [pull_request, workflow_dispatch]

jobs:
  if_merged:
    if: github.event.pull_request.merged == false
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Installing Choco
        shell: pwsh
        run: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      # - name: Install tooling with Choco
      #   shell: pwsh
      #   run: |
      #       choco install cmake.install --version=3.31.6
      #       cmake --version
      #       choco install llvm --version=20.1.4
      #       clang++ --version
      #       choco install git make mingw

      # # - name: Installing Vulkan SDK
      # #   shell: pwsh
      # #   # run: winget install --id=KhronosGroup.VulkanSDK -e --accept-licenses --default-answer --confirm-command install
      # #   run: |
      # #     winget install --id=KhronosGroup.VulkanSDK -e --force --silent --accept-package-agreements --accept-source-agreements
      # - name: Install Vulkan SDK
      #   uses: humbletim/setup-vulkan-sdk@v1.2.1
      #   with:
      #     vulkan-query-version: 1.4.304.1
      #     vulkan-components: Vulkan-Headers, Vulkan-Loader
      #     vulkan-use-cache: true

      
      - name: Pip installing conan
        shell: pwsh
        run: pip install conan
      
      - name: Setting up conan profiles
        shell: pwsh
        run: conan config install -sf profiles/x86_64/Windows/ -tf profiles https://github.com/engine3d-dev/conan-config.git
      
      - name: Setting up Remote Repositories
        shell: pwsh
        run: |
          conan remote add engine3d-conan https://libhal.jfrog.io/artifactory/api/conan/engine3d-conan
          conan remote add libhal-trunk https://libhal.jfrog.io/artifactory/api/conan/trunk-conan

      - name: Login to JFrog
        env:
            PASSWORD: ${{ secrets.JFROG_USER_TOKEN_ID }}
            JFROG_USER: ${{ secrets.JFROG_USERNAME }}
        run: conan remote login -p 1234 engine3d-conan test@gmail.com
      
      # - name: Building vulkan-cpp
      #   shell: pwsh
      #   run: |
      #       conan create . -b missing -s build_type=Release -pr windows_x86_64
      #       conan create . -b missing -s build_type=Debug -pr windows_x86_64
      #       conan create . -b missing -s build_type=MinSizeRel -pr windows_x86_64