name: Deploy to MacOS Armv8

# on:
#   pull_request:
#     types: [closed]
#     branches:
#       - main  # Only trigger for PRs merged into main

on: [pull_request, workflow_dispatch]

jobs:
  macos_armv8:
    if: github.event.pull_request.merged == false
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install LLVM
        run: brew install python pipx llvm@20

      - name: Install Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.1
        with:
          vulkan-query-version: 1.4.304.1
          vulkan-components: Vulkan-Headers, Vulkan-Loader
          vulkan-use-cache: true

      - name: Pipx installing conan
        shell: pwsh
        run: |
            pipx install "conan>=2.18.2"
            pipx upgrade conan
      
      - name: Setting up conan profiles
        shell: pwsh
        run: conan config install -sf profiles/armv8/mac/ -tf profiles https://github.com/engine3d-dev/conan-config.git
      
      - name: Setting up Remote Repositories
        shell: pwsh
        run: |
          conan remote add engine3d-conan https://libhal.jfrog.io/artifactory/api/conan/engine3d-conan
          conan remote add libhal-trunk https://libhal.jfrog.io/artifactory/api/conan/trunk-conan

      - name: Creating Release build for vulkan-cpp 
        shell: pwsh
        run: conan create . -b missing -s build_type=Release -pr mac_armv8
      
      - name: Creating Debug build for vulkan-cpp 
        shell: pwsh
        run: conan create . -b missing -s build_type=Debug -pr mac_armv8
      
      - name: Creating MinSizeRel build for vulkan-cpp
        shell: pwsh
        run: conan create . -b missing -s build_type=MinSizeRel -pr mac_armv8
      
      - name: Login to JFrog
        run: conan remote login -p ${{ secrets.JFROG_USER_TOKEN_ID }} engine3d-conan ${{ secrets.JFROG_USERNAME }}
      
      # - name: Uploading vulkan-cpp to engine3d-conan remote repositories
      #   shell: pwsh
      #   run: conan upload vulkan-cpp/4.0 --r=engine3d-conan --confirm