name: Macos Build Tests

on: [pull_request]

jobs:
    macos-build:
        name: "M1 Mac Build"
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install Homebrew
              run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

            - name: Install LLVM
              run: |
                brew install python pipx llvm@20

            - name: Install Vulkan SDK
              run: |
                curl -O https://sdk.lunarg.com/sdk/download/1.4.335.1/mac/vulkansdk-macos-1.4.335.1.zip
                unzip vulkansdk-macos-1.4.335.1.zip
                # Navigate to the installer directory
                cd vulkansdk-macOS-1.4.335.1.app

                # Run the installer (requires sudo for system-wide installation)
                # Replace '~/VulkanSDK/1.4.335.1' with your preferred installation path
                ls vulkansdk-macOS-1.4.335.1.app/Contents/MacOS
                sudo ./vulkansdk-macOS-1.4.335.1.app/Contents/MacOS/vulkansdk-macOS-1.4.335.1 \
                    --root ~/VulkanSDK/1.4.335.1 \
                    --accept-licenses \
                    --default-answer \
                    --confirm-command install
                source ~/VulkanSDK/1.4.335.1/setup-env.sh
                export VULKAN_SDK=$HOME/VulkanSDK/1.4.335.1/macOS
                export PATH=$VULKAN_SDK/bin:$PATH
                export DYLD_LIBRARY_PATH=$VULKAN_SDK/lib:$DYLD_LIBRARY_PATH
                export VK_ICD_FILENAMES=$VULKAN_SDK/share/vulkan/icd.d/MoltenVK_icd.json
                export VK_LAYER_PATH=$VULKAN_SDK/share/vulkan/explicit_layer.d
                vulkaninfo --summary


            - name: Installing conan
              run: |
                pipx install "conan>=2.18.2"
                pipx upgrade conan

            - name: Installing clang-tidy
              run: sudo ln -s $(brew --prefix llvm)/bin/clang-tidy /usr/local/bin/

            - name: Install Rosetta
              run: /usr/sbin/softwareupdate --install-rosetta --agree-to-license

            - name: Setting up Conan profile
              run: conan config install -sf profiles/armv8/mac/ -tf profiles https://github.com/engine3d-dev/conan-config.git

            - name: Installing Atlas repositories
              run: |
                conan remote add engine3d-conan https://libhal.jfrog.io/artifactory/api/conan/engine3d-conan
                conan remote add libhal-trunk https://libhal.jfrog.io/artifactory/api/conan/trunk-conan

            - name: Building vulkan-cpp
              run: |
                conan create . -b missing -s build_type=Release -pr mac_armv8
                conan create . -b missing -s build_type=Debug -pr mac_armv8
                conan create . -b missing -s build_type=MinSizeRel -pr mac_armv8